# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DailyGreen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod	'KakaoSDKCommon' #kakao 공통 모듈
  pod	'KakaoSDKAuth'  #kakao 로그인
  pod	'KakaoSDKUser'
  # Pods for DailyGreen

  target 'DailyGreenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DailyGreenUITests' do
    # Pods for testing
  end

end
