# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '13.0'
use_frameworks!


target 'DailyGreen' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 	'XLPagerTabStrip', '~> 9.0'
  pod	'KakaoSDKCommon' #kakao 공통 모듈
  pod	'KakaoSDKAuth'  #kakao 로그인
  pod	'KakaoSDKUser'
  pod	'KakaoSDKTalk'
  pod   "BSImagePicker", "~> 3.1"

  # Pods for DailyGreen

  target 'DailyGreenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DailyGreenUITests' do
    # Pods for testing
  end

end
